name: Python application
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.10.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5  
      - run: pip install -r requirements.txt
      - name: Run tests
        run: |
         sleep 5 & pytest py_test.py | timeout 10 uvicorn main:app --reload
         if [[ $? -eq 124 ]]
         then exit 1
         else exit 0
         fi
