name: Python application
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.10.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5  
      - run: pip install -r requirements.txt
      - name: Run tests
        run: |
         timeout 15 || err=$?
         if [[$err -eq 255]]
         then
          exit 0
         else
          uvicorn main:app --reload | pytest py_test.py
          exit 1
         fi
       
